### ISSUE TITLE
taskContent with 'ng-click',doesn't work

### ISSUE THREAD

**Issue by zhendong590** [angular-gantt/angular-gantt#388]
when i use task-content attribute to add a icon ,it works fine,however add `ng-click` it cann't  listen the event ,code is 

```html
<div gantt
                 data=ganttdata
                 task-content="taskContent">
                <gantt-tree></gantt-tree>
                <gantt-movable></gantt-movable>
                <gantt-tooltips></gantt-tooltips>
                <gantt-draw-task enabled="true"
                                 task-factory="drawTaskFactory">
                </gantt-draw-task>
                <gantt-resize-sensor enabled="true">
                </gantt-resize-sensor>
                <gantt-progress enabled="true"></gantt-progress>
</div>
```

and script is
```javascript
$scope.taskContent = "<i class='fa fa-cog' ng-click='editTaskContent()'></i>{{task.model.name}}";
```

**Comment by zhendong590** [comment]
i guess Maybe it affected by other elements in the DOM,they override it, is there any method can fix it .

**Comment by Toilal** [comment]
angular-gantt define a default CSS property that disable pointer events on many elements.

```css
.gantt-side-content, .gantt-body {
    pointer-events: none;
}

.gantt-side-background, .gantt-body-background, .gantt-task, .gantt-row {
    pointer-events: auto;
}

.gantt a, .gantt input {
    pointer-events: auto;
}
```

Try to add `pointer-events: auto` to elements you want to handle click properly. Or use a link, like this

```js
$scope.taskContent = "<a href="ng-click='editTaskContent()'"><i class='fa fa-cog'></i></a> {{task.model.name}}";
```

This should be documented somewhere though.

Please tell me if you have fixed this issue using a link.

**Comment by zhendong590** [comment]
@Toilal  Thanks ! I update my code according to your suggestion.it also doesn't work. I try:
```javascript
$scope.taskContent ="<a class=\"gantt-link\" href=\"ng-click='editTaskContent()'\"><i class=\"fa fa-cog\"></i></a>{{task.model.name}}";
```
and css:
```css
.gantt-link{
    pointer-events:auto;
}
```
