### ISSUE TITLE
Header height changing

### ISSUE THREAD

**Issue by paveldayneko** [angular-gantt/angular-gantt#509]
Hi, I would like to change header's height but I've stuck with it. I cant find ganttHeaderHeight option anywhere. As I can see this option is responsible for header's height, but I can't find where this option is setting up or changing. Please advice.
Thanks

**Comment by Toilal** [comment]
It can be customized with some CSS.

```css
.gantt-header-row, .gantt-header-row .gantt-column-header {
    height: 60px;
}
```
