### ISSUE TITLE
How do you change the highlight colour of the current day?

### ISSUE THREAD

**Issue by B3nCr** [angular-gantt/angular-gantt#680]

**Comment by andrepaulo** [comment]
for the currentDay (which is not what you're showing in your print ( this is a holliday ))you just need to override this class:

``` CSS
.gantt-foreground-col-current-date {
    background-color: orangered;
    opacity: 0.6
}
```
I've changed from ``green`` to ``orangered``
