### ISSUE TITLE
Task completed in percentage 

### ISSUE THREAD

**Issue by ShanmugapriyaDurairaj** [angular-gantt/angular-gantt#741]
Hi, 

How can we show task completed in percentage like below image 

![untitled1](https://cloud.githubusercontent.com/assets/18119327/25472933/fbfc5d0a-2b4a-11e7-98ab-560d1da29742.png)

**Comment by Toilal** [comment]
```css
.gantt-task-progress {
    height: 100%
}
```
